CREATE DATABASE NOMINA_HS;
USE NOMINA_HS;
/*DROP DATABASE NOMINA_HS;*/

CREATE TABLE ESTADO(
ID_ESTADO INT AUTO_INCREMENT PRIMARY KEY,
ESTADO VARCHAR(15)
);



CREATE TABLE ROL
(
ID_ROL INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR (60) NOT NULL,
ESTADO_ROL INT, 
FOREIGN KEY (ESTADO_ROL) REFERENCES ESTADO(ID_ESTADO),
UNIQUE(NOMBRE)
);

CREATE TABLE CARGO 
(
ID_CARGO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_CARGO VARCHAR (60) NOT NULL,
ESTADO_ID INT,
FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID_ESTADO),
UNIQUE(NOMBRE_CARGO)
);

CREATE TABLE OBRA
(
ID_OBRA INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_OBRA VARCHAR (60) NOT NULL,
REPRESENTANTE VARCHAR (60) NOT NULL,
DIRECCION_OBRA VARCHAR (150) NOT NULL,
ESTADO_ID INT,
FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID_ESTADO),
UNIQUE(NOMBRE_OBRA, DIRECCION_OBRA)
);

CREATE TABLE CONTRATO 
(
ID_CONTRATO INT PRIMARY KEY AUTO_INCREMENT,
TIPO_CONTRATO VARCHAR (60) NOT NULL,
DESCRIPCION VARCHAR (100) NOT NULL,
ESTADO_ID INT,
FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID_ESTADO),
UNIQUE(TIPO_CONTRATO)
);

CREATE TABLE DEPARTAMENTO 
(
ID_DPTO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_DPTO VARCHAR (60) NOT NULL,
DESCRIPCION_DPTO VARCHAR (150) NOT NULL,
ESTADO_ID INT,
FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID_ESTADO),
UNIQUE(NOMBRE_DPTO)
);

CREATE TABLE EMPLEADO
(
ID_EMPLEADO INT PRIMARY KEY,
NOMBRES VARCHAR (30) NOT NULL,
APELLIDOS VARCHAR (50) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
DIRECCION VARCHAR (100) NOT NULL,
TELEFONO VARCHAR (11) NOT NULL,
SALARIO INT NOT NULL,
ID_CARGO_FK INT NOT NULL,
ID_OBRA_FK INT NOT NULL,
ID_CONTRATO_FK INT NOT NULL,
ID_DEPARTAMENTO_FK INT NOT NULL,
ESTADO_ID INT,
FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID_ESTADO),
UNIQUE(DIRECCION, TELEFONO)
);
CREATE TABLE USUARIOS
(
ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT, 
ID_ROL_FK INT NOT NULL,
USUARIO INT,
CONTRASEÑA VARCHAR (30) NOT NULL,
ESTADO_ID INT,
FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID_ESTADO),
FOREIGN KEY (USUARIO) REFERENCES EMPLEADO(ID_EMPLEADO)
);
ALTER TABLE USUARIOS CHANGE CONTRASEÑA  CONTRASENA VARCHAR(30);
alter table USUARIOS ADD CORREO VARCHAR(100);
CREATE TABLE TIPO_NOVEDAD 
(
ID_TIPONOVEDAD INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_TN VARCHAR (60) NOT NULL,
DESCRIPCION VARCHAR (200) NOT NULL,
PORCENTAJE DECIMAL,
ESTADO_ID INT,
FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID_ESTADO),
UNIQUE (NOMBRE_TN)
);
alter table TIPO_NOVEDAD modify PORCENTAJE DECIMAL(2,2);


CREATE TABLE NOVEDAD 
(
ID_NOVEDAD INT PRIMARY KEY AUTO_INCREMENT,
ID_USUARIOS_FK INT NOT NULL,
TIPO_NOVEDAD_FK INT NOT NULL,
EMPLEADOFK INT  NOT NULL,
FECHA_INICIO DATETIME  NULL,
FECHA_FIN DATETIME  NULL,
VALOR INT NOT NULL,
ESTADO_ID INT,
FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID_ESTADO)
);




ALTER TABLE EMPLEADO ADD FOREIGN KEY (ID_CARGO_FK) REFERENCES CARGO (ID_CARGO);
ALTER TABLE EMPLEADO ADD FOREIGN KEY (ID_OBRA_FK) REFERENCES OBRA (ID_OBRA);
ALTER TABLE EMPLEADO ADD FOREIGN KEY (ID_CONTRATO_FK) REFERENCES CONTRATO (ID_CONTRATO);
ALTER TABLE EMPLEADO ADD FOREIGN KEY (ID_DEPARTAMENTO_FK) REFERENCES DEPARTAMENTO (ID_DPTO);
ALTER TABLE NOVEDAD ADD FOREIGN KEY (ID_USUARIOS_FK) REFERENCES USUARIOS (ID_USUARIO);
ALTER TABLE NOVEDAD ADD FOREIGN KEY (TIPO_NOVEDAD_FK) REFERENCES TIPO_NOVEDAD (ID_TIPONOVEDAD);
ALTER TABLE NOVEDAD ADD CONSTRAINT NOVEMPLEADOFK FOREIGN KEY (EMPLEADOFK) REFERENCES EMPLEADO (ID_EMPLEADO);
ALTER TABLE USUARIOS ADD FOREIGN KEY (ID_ROL_FK) REFERENCES ROL (ID_ROL);

/*ESTADO*/
INSERT INTO ESTADO (ESTADO) VALUES ('ACTIVO');
INSERT INTO ESTADO (ESTADO) VALUES ('INACTIVO');

SELECT * FROM DEPARTAMENTO;
INSERT INTO DEPARTAMENTO (NOMBRE_DPTO,DESCRIPCION_DPTO ,ESTADO_ID) VALUES ('SUPERVISIÓN', 'SUPERVISION DE LOS DEPARTAMENTOS',1);
INSERT INTO DEPARTAMENTO (NOMBRE_DPTO,DESCRIPCION_DPTO ,ESTADO_ID) VALUES ('CONSTRUCCIÓN', 'CONSTRUCCION DE OBRA',1);
INSERT INTO DEPARTAMENTO (NOMBRE_DPTO,DESCRIPCION_DPTO ,ESTADO_ID) VALUES ('ENCARGADO DE OBRA', 'ENCARGADO DE GESTIONAR LAS OBRAS',1);

SELECT * FROM CONTRATO;
INSERT INTO CONTRATO (TIPO_CONTRATO,DESCRIPCION ,ESTADO_ID) VALUES ('ACTIVO', 'EL CONTRATO SE ENCUENTRA ACTIVO',1);
INSERT INTO CONTRATO (TIPO_CONTRATO,DESCRIPCION ,ESTADO_ID)VALUES ('INACTIVO', 'EL CONTRATO SE ENCUENTRA INACTIVO',1);
INSERT INTO CONTRATO (TIPO_CONTRATO,DESCRIPCION ,ESTADO_ID)VALUES ('EN ESPERA', 'EL CONTRATO SE ENCUENTRA EN ESPERA',1);

SELECT * FROM OBRA;
INSERT INTO OBRA (NOMBRE_OBRA,REPRESENTANTE,DIRECCION_OBRA,ESTADO_ID)VALUES  ( 'CASTILLA II', 'ANDRES RODRIGUEZ', 'CRA 90 K',1);
INSERT INTO OBRA (NOMBRE_OBRA,REPRESENTANTE,DIRECCION_OBRA,ESTADO_ID)VALUES ( 'CASTILLA III', 'ANDRES RODRIGUEZ', 'CRA 100 K',1);
INSERT INTO OBRA (NOMBRE_OBRA,REPRESENTANTE,DIRECCION_OBRA,ESTADO_ID)VALUES ( 'CASTILLA IV', 'ANDRES RODRIGUEZ', 'CRA 150 K',1);

SELECT * FROM ROL;
INSERT INTO ROL (NOMBRE,ESTADO_ROL ) VALUES ('Administrador', 1);
INSERT INTO ROL (NOMBRE,ESTADO_ROL ) VALUES ('Empleado', 1);

SELECT * FROM CARGO;
INSERT INTO CARGO (NOMBRE_CARGO,ESTADO_ID)VALUES ('GERENTE',1);
INSERT INTO CARGO (NOMBRE_CARGO,ESTADO_ID)VALUES ('EMPLEADO',1);
INSERT INTO CARGO (NOMBRE_CARGO,ESTADO_ID)VALUES ('SUPERVISOR',1);
 SELECT * FROM EMPLEADO;
INSERT INTO EMPLEADO VALUES (4, 'ANDRES', 'RINCON', '2014-03-12', 'cra 77 hg', 302541, 900000, 1, 2, 3, 1,1);
INSERT INTO EMPLEADO VALUES (5, 'SANTIAGO', 'RINCON', '2014-03-10', 'cra 74 hg', 304541, 900000, 2, 3, 1, 2,1);
INSERT INTO EMPLEADO VALUES (6, 'FELIPE', 'RINCON', '2014-03-11', 'cra 78 hg', 302441, 900000, 3, 1, 2, 3,1);

SELECT * FROM USUARIOS;
INSERT INTO USUARIOS (ID_ROL_FK,USUARIO,CONTRASEÑA,ESTADO_ID)VALUES (1, 4, 'andres123', 1);
INSERT INTO USUARIOS ( ID_ROL_FK,USUARIO,CONTRASEÑA,ESTADO_ID)VALUES (2, 5, 'santiago123', 1);
INSERT INTO USUARIOS ( ID_ROL_FK,USUARIO,CONTRASEÑA,ESTADO_ID)VALUES (2, 6, 'felipe123', 1);


SELECT * FROM TIPO_NOVEDAD;
INSERT INTO TIPO_NOVEDAD (NOMBRE_TN,DESCRIPCION,PORCENTAJE,ESTADO_ID) VALUES ('Hora Extra', 'SE ENCUENTRA ACTIVO',0.04,1);
INSERT INTO TIPO_NOVEDAD (NOMBRE_TN,DESCRIPCION,PORCENTAJE,ESTADO_ID)VALUES ('INACTIVO', 'SE ENCUENTRA INACTIVO',0.04,1);
INSERT INTO TIPO_NOVEDAD (NOMBRE_TN,DESCRIPCION,PORCENTAJE,ESTADO_ID)VALUES ( 'EN ESPERA', 'SE ENCUENTRA EN ESPERA',0.04,1);


SELECT * FROM NOVEDAD;
INSERT INTO NOVEDAD (ID_USUARIOS_FK,TIPO_NOVEDAD_FK ,EMPLEADOFK ,FECHA_INICIO,FECHA_FIN,VALOR,ESTADO_ID) VALUES (1, 3, 4, '2014-03-10 06:30:00', '2014-03-11 12:30:00',50000,1);
INSERT INTO NOVEDAD (ID_USUARIOS_FK,TIPO_NOVEDAD_FK ,EMPLEADOFK ,FECHA_INICIO,FECHA_FIN,VALOR,ESTADO_ID)VALUES ( 2, 2, 5, '2014-03-10 06:30:00','2014-03-11 14:30:00', 50000,1);
INSERT INTO NOVEDAD (ID_USUARIOS_FK,TIPO_NOVEDAD_FK ,EMPLEADOFK ,FECHA_INICIO,FECHA_FIN,VALOR,ESTADO_ID)VALUES ( 3, 1, 6, '2014-03-11 07:30:00','2014-03-11 14:30:00', 50000,1);








CREATE VIEW VISTA_EMPLEADOS AS
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO = 1;
SELECT * FROM NOMINA_HS.VISTA_EMPLEADOS;

CREATE VIEW VISTA_DATOSEMP AS
SELECT * FROM EMPLEADO ORDER BY ID_EMPLEADO DESC;
SELECT * FROM NOMINA_HS.VISTA_DATOSEMP;

CREATE VIEW VISTA_NOVEDAD  AS
SELECT * FROM NOVEDAD WHERE ID_NOVEDAD = 1;
SELECT * FROM NOMINA_HS.VISTA_NOVEDAD;

CREATE VIEW VISTA_DATOSNOV AS
SELECT * FROM NOVEDAD ORDER BY ID_NOVEDAD DESC;
SELECT * FROM NOMINA_HS.VISTA_DATOSNOV;

CREATE VIEW VISTA_TN AS
SELECT * FROM TIPO_NOVEDAD WHERE ID_TIPONOVEDAD = 1;
SELECT * FROM NOMINA_HS.VISTA_TN;

CREATE VIEW VISTA_DATOSTN AS
SELECT * FROM TIPO_NOVEDAD ORDER BY ID_TIPONOVEDAD DESC;
SELECT * FROM NOMINA_HS.VISTA_DATOSTN;

CREATE VIEW VISTA_USUARIOS AS
SELECT * FROM USUARIOS WHERE ID_USUARIO = 1;
SELECT * FROM NOMINA_HS.VISTA_USUARIOS;

CREATE VIEW VISTA_DATOSUSU AS
SELECT * FROM USUARIOS ORDER BY ID_USUARIO DESC;
SELECT * FROM NOMINA_HS.VISTA_DATOSUSU;

CREATE VIEW VISTA_ROL AS
SELECT * FROM ROL WHERE ID_ROL = 1;
SELECT * FROM NOMINA_HS.VISTA_ROL;

CREATE VIEW VISTA_DATOSROL AS
SELECT * FROM ROL ORDER BY ID_ROL DESC;
SELECT * FROM NOMINA_HS.VISTA_DATOSROL;

CREATE VIEW VISTA_CARGO AS
SELECT * FROM CARGO WHERE ID_CARGO = 1;
SELECT * FROM NOMINA_HS.VISTA_CARGO;

CREATE VIEW VISTA_DATOSCAR AS
SELECT * FROM CARGO ORDER BY ID_CARGO DESC;
SELECT * FROM NOMINA_HS.VISTA_DATOSCAR;

CREATE VIEW VISTA_OBRA AS
SELECT * FROM OBRA WHERE ID_OBRA = 1;
SELECT * FROM NOMINA_HS.VISTA_OBRA;

CREATE TABLE VISTA_DATOSOBRA AS
SELECT * FROM OBRA ORDER BY ID_OBRA DESC;
SELECT * FROM NOMINA_HS.VISTA_DATOSOBRA;

CREATE VIEW VISTA_CONTRATO AS
SELECT * FROM CONTRATO WHERE ID_CONTRATO = 1;
SELECT * FROM NOMINA_HS.VISTA_CONTRATO;

CREATE VIEW VISTA_DATOSCON AS
SELECT * FROM CONTRATO ORDER BY ID_CONTRATO DESC;
SELECT * FROM NOMINA_HS.VISTA_DATOSCON;

CREATE VIEW VISTA_DPTO AS
SELECT * FROM DEPARTAMENTO WHERE ID_DPTO = 1;
SELECT * FROM NOMINA_HS.VISTA_DPTO;

CREATE VIEW VISTA_DATOSDPTO AS
SELECT * FROM DEPARTAMENTO ORDER BY ID_DPTO DESC;
SELECT * FROM NOMINA_HS.VISTA_DATOSDPTO;




DELIMITER $$
USE NOMINA_HS $$
CREATE PROCEDURE PROC_EMPLEADO(
	IN _ID_EMPLEADO INT, 
    IN _NOMBRES VARCHAR (30),
    IN _APELLIDOS VARCHAR (50),
    IN _FECHA_INGRESO DATETIME,
    IN _DIRECCION VARCHAR (100),
    IN _TELEFONO VARCHAR (100),
    IN _SALARIO INT,
    IN _ID_CARGO_FK INT,
    IN _ID_OBRA_FK INT,
    IN _ID_CONTRATO_FK INT,
    IN _ID_DEPARTAMENTO_FK INT,
    IN ACCION VARCHAR (60)
)
BEGIN
	CASE ACCION
		WHEN 'NUEVO' THEN
			INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRES, APELLIDOS, FECHA_INGRESO, DIRECCION, TELEFONO, SALARIO, ID_CARGO_FK, ID_OBRA_FK, ID_CONTRATO_FK, ID_DEPARTAMENTO_FK)
            VALUES (_ID_EMPLEADO, _NOMBRES, _APELLIDOS, _FECHA_INGRESO, _DIRECCION, _TELEFONO, _SALARIO, _ID_CARGO_FK, _ID_OBRA_FK, _ID_CONTRATO_FK, _ID_DEPARTAMENTO_FK);
        WHEN 'EDITAR' THEN    
            UPDATE EMPLEADO SET
            ID_EMPLEADO=_ID_EMPLEADO, NOMBRES=_NOMBRES, APELLIDOS=_APELLIDOS, FECHA_INGRESO=_FECHA_INGRESO, DIRECCION=_DIRECCION, TELEFONO=_TELEFONO, SALARIO=_SALARIO, ID_CARGO_FK=_ID_CARGO_FK, ID_OBRA_FK=_ID_OBRA_FK, ID_CONTRATO_FK=_ID_CONTRATO_FK, ID_DEPARTAMENTO_FK=_ID_DEPARTAMENTO_FK
            WHERE ID_EMPLEADO=_ID_EMPLEADO;
		WHEN 'CONSULTAR' THEN 
			SELECT * FROM EMPLEADO WHERE ID_EMPLEADO=_ID_EMPLEADO;
		WHEN 'ELIMINAR' THEN 
			DELETE FROM EMPLEADO WHERE ID_EMPLEADO=_ID_EMPLEADO;
    END CASE;
END$$

DELIMITER $$
USE NOMINA_HS $$
CREATE PROCEDURE PROC_NOVEDAD(
	IN _ID_NOVEDAD INT, 
    IN _ID_USUARIOS_FK INT,
    IN _TIPO_NOVEDAD_FK INT,
    IN _ID_EMPLEADO_FK INT,
    IN _DIAS DATETIME,
    IN _VALOR INT,
    IN ACCION VARCHAR (60)
)
BEGIN
	CASE ACCION
		WHEN 'NUEVO' THEN
			INSERT INTO NOVEDAD (ID_NOVEDAD, ID_USUARIOS_FK, TIPO_NOVEDAD_FK, ID_EMPLEADO_FK, DIAS, VALOR)
            VALUES (_ID_NOVEDAD, _ID_USUARIOS_FK, _TIPO_NOVEDAD_FK, _ID_EMPLEADO_FK, _DIAS, _VALOR);
        WHEN 'EDITAR' THEN    
            UPDATE NOVEDAD SET
            ID_NOVEDAD=_ID_NOVEDAD, ID_USUARIOS_FK=_ID_USUARIOS_FK, TIPO_NOVEDAD_FK=_TIPO_NOVEDAD_FK, ID_EMPLEADO_FK=_ID_EMPLEADO_FK, DIAS=_DIAS, VALOR=_VALOR
            WHERE ID_NOVEDAD=_ID_NOVEDAD;
		WHEN 'CONSULTAR' THEN 
			SELECT * FROM NOVEDAD WHERE ID_NOVEDAD=_ID_NOVEDAD;
		WHEN 'ELIMINAR' THEN 
			DELETE FROM NOVEDAD WHERE ID_NOVEDAD=_ID_NOVEDAD;
    END CASE;
END$$

DELIMITER $$
USE NOMINA_HS $$
CREATE PROCEDURE PROC_TNOVEDAD(
	IN _ID_TIPONOVEDAD INT, 
    IN _NOMBRE_TN VARCHAR (60),
    IN _DESCRIPCION VARCHAR (200),
    IN ACCION VARCHAR (60)
)
BEGIN
	CASE ACCION
		WHEN 'NUEVO' THEN
			INSERT INTO TIPO_NOVEDAD (ID_TIPONOVEDAD, NOMBRE_TN, DESCRIPCION)
            VALUES (_ID_TIPONOVEDAD, _NOMBRE_TN, _DESCRIPCION);
        WHEN 'EDITAR' THEN    
            UPDATE TIPO_NOVEDAD SET
            ID_TIPONOVEDAD=_ID_TIPONOVEDAD, NOMBRE_TN=_NOMBRE_TN, DESCRIPCION=_DESCRIPCION
            WHERE ID_TIPONOVEDAD=_ID_TIPONOVEDAD;
		WHEN 'CONSULTAR' THEN 
			SELECT * FROM TIPO_NOVEDAD WHERE ID_TIPONOVEDAD=_ID_TIPONOVEDAD;
		WHEN 'ELIMINAR' THEN 
			DELETE FROM TIPO_NOVEDAD WHERE ID_TIPONOVEDAD=_ID_TIPONOVEDAD;
    END CASE;
END$$

DELIMITER $$
USE NOMINA_HS $$
CREATE PROCEDURE PROC_USUARIOS(
	IN _ID_USUARIOS INT, 
    IN _ID_ROL_FK INT,
    IN _CONTRASEÑA VARCHAR(30),
    IN _ESTADO INT,
    IN ACCION VARCHAR (60)
)
BEGIN
	CASE ACCION
		WHEN 'NUEVO' THEN
			INSERT INTO USUARIOS (ID_USUARIOS, ID_ROL_FK, CONTRASEÑA, ESTADO)
            VALUES (_ID_USUARIOS, _ID_ROL_FK, _CONTRASEÑA, _ESTADO);
        WHEN 'EDITAR' THEN    
            UPDATE USUARIOS SET
            ID_USUARIOS=_ID_USUARIOS, ID_ROL_FK=_ID_ROL_FK, CONTRASEÑA=_CONTRASEÑA, ESTADO=_ESTADO
            WHERE ID_USUARIOS = _ID_USUARIOS;
		WHEN 'CONSULTAR' THEN 
			SELECT * FROM USUARIOS WHERE ID_USUARIOS = _ID_USUARIOS;
		WHEN 'ELIMINAR' THEN 
			DELETE FROM USUARIOS WHERE ID_USUARIOS = _ID_USUARIOS;
    END CASE;
END$$

DELIMITER $$
USE NOMINA_HS $$
CREATE PROCEDURE PROC_ROL(
	IN _ID_ROL INT, 
    IN _NOMBRE VARCHAR (60),
    IN _ESTADO_ROL INT,
    IN ACCION VARCHAR (60)
)
BEGIN
	CASE ACCION
		WHEN 'NUEVO' THEN
			INSERT INTO ROL (ID_ROL, NOMBRE, ESTADO_ROL)
            VALUES (_ID_ROL, _NOMBRE, _ESTADO_ROL);
        WHEN 'EDITAR' THEN    
            UPDATE ROL SET
            ID_ROL=_ID_ROL, NOMBRE=_NOMBRE, ESTADO_ROL=_ESTADO_ROL
            WHERE ID_ROL=_ID_ROL;
		WHEN 'CONSULTAR' THEN 
			SELECT * FROM ROL WHERE ID_ROL=_ID_ROL;
		WHEN 'ELIMINAR' THEN 
			DELETE FROM ROL WHERE ID_ROL=_ID_ROL;
    END CASE;
END$$

DELIMITER $$
USE NOMINA_HS $$
CREATE PROCEDURE PROC_CARGO(
	IN _ID_CARGO INT, 
    IN _NOMBRE VARCHAR (60),
    IN ACCION VARCHAR (60)
)
BEGIN
	CASE ACCION
		WHEN 'NUEVO' THEN
			INSERT INTO CARGO (ID_CARGO, NOMBRE_CARGO)
            VALUES (_ID_CARGO, _NOMBRE_CARGO);
        WHEN 'EDITAR' THEN    
            UPDATE CARGO SET
            ID_CARGO=_ID_CARGO, NOMBRE_CARGO=_NOMBRE_CARGO
            WHERE ID_CARGO=_ID_CARGO;
		WHEN 'CONSULTAR' THEN 
			SELECT * FROM CARGO WHERE ID_CARGO=_ID_CARGO;
		WHEN 'ELIMINAR' THEN 
			DELETE FROM CARGO WHERE ID_CARGO=_ID_CARGO;
    END CASE;
END$$

DELIMITER $$
USE NOMINA_HS $$
CREATE PROCEDURE PROC_OBRA(
	IN _ID_OBRA INT, 
    IN _NOMBRE_OBRA VARCHAR (60),
    IN _REPRESENTANTE VARCHAR (60),
    IN _DIRECCION_OBRA VARCHAR (150),
    IN ACCION VARCHAR (60)
)
BEGIN
	CASE ACCION
		WHEN 'NUEVO' THEN
			INSERT INTO OBRA (ID_OBRA, NOMBRE_OBRA, REPRESENTANTE, DIRECCION_OBRA)
            VALUES (_ID_OBRA, _NOMBRE_OBRA, _REPRESENTANTE, _DIRECCION_OBRA);
        WHEN 'EDITAR' THEN    
            UPDATE OBRA SET
            ID_OBRA=_ID_OBRA, NOMBRE_OBRA=_NOMBRE_OBRA, REPRESENTANTE=_REPRESENTANTE, DIRECCION_OBRA=_DIRECCION_OBRA
            WHERE ID_USUARIOS = _ID_USUARIOS;
		WHEN 'CONSULTAR' THEN 
			SELECT * FROM OBRA WHERE ID_OBRA=_ID_OBRA;
		WHEN 'ELIMINAR' THEN 
			DELETE FROM OBRA WHERE ID_OBRA=_ID_OBRA;
    END CASE;
END$$

DELIMITER $$
USE NOMINA_HS $$
CREATE PROCEDURE PROC_CONTRATO(
	IN _ID_CONTRATO INT, 
    IN _TIPO_CONTRATO VARCHAR (60),
    IN _DESCRIPCION VARCHAR (100),
    IN ACCION VARCHAR (60)
)
BEGIN
	CASE ACCION
		WHEN 'NUEVO' THEN
			INSERT INTO CONTRATO (ID_CONTRATO, TIPO_CONTRATO, DESCRIPCION)
            VALUES (_ID_CONTRATO, _TIPO_CONTRATO, _DESCRIPCION);
        WHEN 'EDITAR' THEN    
            UPDATE CONTRATO SET
            ID_CONTRATO=_ID_CONTRATO, TIPO_CONTRATO=_TIPO_CONTRATO, DESCRIPCION=_DESCRIPCION
            WHERE ID_CONTRATO=_ID_CONTRATO;
		WHEN 'CONSULTAR' THEN 
			SELECT * FROM CONTRATO WHERE ID_CONTRATO=_ID_CONTRATO;
		WHEN 'ELIMINAR' THEN 
			DELETE FROM CONTRATO WHERE ID_CONTRATO=_ID_CONTRATO;
    END CASE;
END$$

DELIMITER $$
USE NOMINA_HS $$
CREATE PROCEDURE PROC_DEPARTAMENTO(
	IN _ID_DPTO INT, 
    IN _NOMBRE_DPTO VARCHAR (60),
    IN _DESCRIPCION_DPTO VARCHAR (150),
    IN ACCION VARCHAR (60)
)
BEGIN
	CASE ACCION
		WHEN 'NUEVO' THEN
			INSERT INTO DEPARTAMENTO (ID_DPTO, NOMBRE_DPTO, DESCRIPCION)
            VALUES (_ID_DPTO, _NOMBRE_DPTO, _DESCRIPCION);
        WHEN 'EDITAR' THEN    
            UPDATE DEPARTAMENTO SET
            ID_DPTO=_ID_DPTO, NOMBRE_DPTO=_NOMBRE_DPTO, DESCRIPCION=_DESCRIPCION
            WHERE ID_DPTO=_ID_DPTO;
		WHEN 'CONSULTAR' THEN 
			SELECT * FROM DEPARTAMENTO WHERE ID_DPTO=_ID_DPTO;
		WHEN 'ELIMINAR' THEN 
			DELETE FROM DEPARTAMENTO WHERE ID_DPTO=_ID_DPTO;
    END CASE;
END$$
